// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobIKpPScNa4qw41h6M0WY-RY8954sdjE',
    appId: '1:717527430183:web:4fd04c9ccbc5557fccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    authDomain: 'nudge-5a8d0.firebaseapp.com',
    databaseURL:
        'https://nudge-5a8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nudge-5a8d0.appspot.com',
    measurementId: 'G-T76TBXTD7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6U5Gj2wxP8XP4MUrYEVKixxCYKm0UYE',
    appId: '1:717527430183:android:361cceb30eab578fccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    databaseURL:
        'https://nudge-5a8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nudge-5a8d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzPiUewJyZJvpFNUaJaC7qofcWKV06uA',
    appId: '1:717527430183:ios:def310821c036f3fccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    databaseURL:
        'https://nudge-5a8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nudge-5a8d0.appspot.com',
    androidClientId:
        '717527430183-bfn0ad50voi0flhv2mdt6hj7s31a252j.apps.googleusercontent.com',
    iosClientId:
        '717527430183-dgt907dv0lhenrqb3ovmn0ssq9qu2puq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nudge2',
  );
}
