// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobIKpPScNa4qw41h6M0WY-RY8954sdjE',
    appId: '1:717527430183:web:4fd04c9ccbc5557fccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    authDomain: 'nudge-5a8d0.firebaseapp.com',
    storageBucket: 'nudge-5a8d0.appspot.com',
    measurementId: 'G-T76TBXTD7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA6U5Gj2wxP8XP4MUrYEVKixxCYKm0UYE',
    appId: '1:717527430183:android:48930d0d9d429d21ccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    storageBucket: 'nudge-5a8d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzPiUewJyZJvpFNUaJaC7qofcWKV06uA',
    appId: '1:717527430183:ios:9cbadb0cd930e2bcccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    storageBucket: 'nudge-5a8d0.appspot.com',
    iosClientId: '717527430183-1433uioouhgl6hpjm5l8ojd3lls06po1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nudge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzPiUewJyZJvpFNUaJaC7qofcWKV06uA',
    appId: '1:717527430183:ios:d5f6c3f1844635a3ccca02',
    messagingSenderId: '717527430183',
    projectId: 'nudge-5a8d0',
    storageBucket: 'nudge-5a8d0.appspot.com',
    iosClientId: '717527430183-cokceip50qf6urdee9fl394ih7dti9cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nudge.RunnerTests',
  );
}
